version: '3.8'
services:
  spotyphie-soap-db:
    image: mysql:latest
    restart: always
    container_name: spotyphie-soap-db
    ports:
      - ${MYSQL_MAPPED_PORT}:${MYSQL_MAPPED_PORT}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  spotyphie-soap-service:
    build:
      dockerfile: Dockerfile
    container_name: spotyphie-soap-service
    env_file: .env
    volumes:
      - ./src/:/var/www/html/src
    ports:
      - ${SOAP_MAPPED_PORT}:${SOAP_MAPPED_PORT}
    depends_on:
      - spotyphie-soap-db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3308
    ports:
      - ${PHPMYADMIN_MAPPED_PORT}:80
    depends_on:
      - spotyphie-soap-db
    links:
      - spotyphie-soap-db
    volumes:
      - /sessions

networks:
  default:  
    external:
      name: spotyphie-monolith_default