
package localhost._8080.premiumservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PremiumServiceImplService", targetNamespace = "http://localhost:8080/premiumservice", wsdlLocation = "http://localhost:8080/premiumservice?wsdl")
public class PremiumServiceImplService
    extends Service
{

    private final static URL PREMIUMSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PREMIUMSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PREMIUMSERVICEIMPLSERVICE_QNAME = new QName("http://localhost:8080/premiumservice", "PremiumServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/premiumservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PREMIUMSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PREMIUMSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PremiumServiceImplService() {
        super(__getWsdlLocation(), PREMIUMSERVICEIMPLSERVICE_QNAME);
    }

    public PremiumServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PREMIUMSERVICEIMPLSERVICE_QNAME, features);
    }

    public PremiumServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PREMIUMSERVICEIMPLSERVICE_QNAME);
    }

    public PremiumServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PREMIUMSERVICEIMPLSERVICE_QNAME, features);
    }

    public PremiumServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PremiumServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PremiumServiceImpl
     */
    @WebEndpoint(name = "PremiumServiceImplPort")
    public PremiumServiceImpl getPremiumServiceImplPort() {
        return super.getPort(new QName("http://localhost:8080/premiumservice", "PremiumServiceImplPort"), PremiumServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PremiumServiceImpl
     */
    @WebEndpoint(name = "PremiumServiceImplPort")
    public PremiumServiceImpl getPremiumServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8080/premiumservice", "PremiumServiceImplPort"), PremiumServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PREMIUMSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PREMIUMSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PREMIUMSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
